workflows:
  version: 2.1
  main:
    jobs:
      - build:
          filters:
            branches:
              only: 
              - develop
              - master
version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Find
          command: find .
      - run:
          name: Restore
          command: dotnet restore ./Supermarket.Core/Supermarket.Core.csproj
      - run:
          name: Build
          command: dotnet build ./Supermarket.Core/Supermarket.Core.csproj
      - run:
          name: Restore
          command: dotnet restore ./Supermarket/Supermarket.csproj
      - run:
          name: Build
          command: dotnet build ./Supermarket/Supermarket.csproj
      - run:
          name: Test
          command: dotnet test ./Supermarket.UnitTests/Supermarket.UnitTests.csproj
