name: .NET Core

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.103
    - name: Install Supermarket.Core dependencies
      run: dotnet restore ./Supermarket.Core/Supermarket.Core.csproj
    - name: Install Supermarket dependencies
      run: dotnet restore ./Supermarket/Supermarket.csproj
    - name: Build Supermarket.Core
      run: dotnet build ./Supermarket.Core/Supermarket.Core.csproj 
    - name: Build Supermarket
      run: dotnet restore ./Supermarket/Supermarket.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test .Supermarket.UnitTests/Supermarket.UnitTests.csproj --no-restore --verbosity normal
